In [1]:
import pickle
import torch
import sys
import os
import numpy as np
from train_utils import *

sys.path.append('..')


In [2]:
print(torch.__version__)


1.9.0


In [3]:
model_name = 'rho_reg_pecco'
trained_model = torch.load('../checkpoints/' + model_name + '.pth',map_location=torch.device('cpu'))
trained_model.eval()

ECCONetwork(
  (conv_fluid): EquiCtsConv2dRho1ToReg()
  (conv_obstacle): EquiCtsConv2dRho1ToReg()
  (dense_fluid): Sequential(
    (0): EquiLinearRho1ToReg()
    (1): EquiLinearRegToReg()
  )
  (convs): ModuleList(
    (0): EquiCtsConv2dRegToReg()
    (1): EquiCtsConv2dRegToReg()
    (2): EquiCtsConv2dRegToReg()
    (3): EquiCtsConv2dRegToRho1()
  )
  (denses): ModuleList(
    (0): EquiLinearRegToReg()
    (1): EquiLinearRegToReg()
    (2): EquiLinearRegToReg()
    (3): Sequential(
      (0): EquiLinearRegToReg()
      (1): EquiLinearRegToRho1()
    )
  )
)

In [4]:
from evaluate_network import evaluate
from datasets.argoverse_lane_loader import read_pkl_data
from argoverse.map_representation.map_api import ArgoverseMap


In [5]:
dataset_path = '../../argoverse_data/rose'
val_path = os.path.join(dataset_path, 'val') #, 'lane_data'
val_dataset = read_pkl_data(val_path, batch_size=1, shuffle=False, repeat=False)


In [13]:
with torch.no_grad():
    total_loss, prediction_gt = evaluate(trained_model, val_dataset,
                                       train_window=4, max_iter=1, 
                                       device='cpu', start_iter=0, 
                                        use_lane=False, batch_size=1)

evaluating.. 1 {'nll': array(5.313828e+22, dtype=float32), 'ADE': 14718157000.0, 'ADE_std': 0.0, 'DE@1s': 2732.9297, 'DE@1s_std': 0.0, 'DE@2s': 43109724.0, 'DE@2s_std': 0.0, 'DE@3s': 275165700000.0, 'DE@3s_std': 0.0}
done


In [12]:
prediction_gt

{11221: (tensor([[ 2.1483e+03,  8.0175e+02],
          [ 2.1486e+03,  8.0134e+02],
          [ 2.1477e+03,  8.0232e+02],
          [ 2.1481e+03,  8.0133e+02],
          [ 2.1372e+03,  8.1296e+02],
          [ 2.1366e+03,  8.0659e+02],
          [ 2.0919e+03,  9.5330e+02],
          [ 2.0984e+03,  8.1225e+02],
          [ 1.9600e+03,  1.3754e+03],
          [ 1.8579e+03, -3.9942e+01],
          [ 1.9109e+03,  3.8494e+03],
          [ 9.8147e+02, -6.6313e+03],
          [ 4.0973e+03,  2.1403e+04],
          [-6.9003e+03, -5.3963e+04],
          [ 2.7576e+04,  1.4643e+05],
          [-7.9871e+04, -3.8950e+05],
          [ 2.4186e+05,  1.0380e+06],
          [-6.5985e+05, -2.7135e+06],
          [ 1.8721e+06,  7.1463e+06],
          [-5.2430e+06, -1.8490e+07],
          [ 1.5595e+07,  4.8216e+07],
          [-4.4300e+07, -1.2490e+08],
          [ 1.2761e+08,  3.2280e+08],
          [-3.8341e+08, -8.4573e+08],
          [ 1.2318e+09,  2.2189e+09],
          [-3.6517e+09, -5.7720e+09],
     

In [38]:
pred

[tensor([[[ 589.4445, 1381.8385]]]),
 tensor([[[ 589.6328, 1381.6088]]]),
 tensor([[[ 589.3992, 1380.2305]]]),
 tensor([[[ 588.9202, 1380.0366]]]),
 tensor([[[ 579.9214, 1367.5590]]]),
 tensor([[[ 584.3655, 1377.3729]]]),
 tensor([[[ 596.6658, 1271.8363]]]),
 tensor([[[ 640.7068, 1356.7920]]]),
 tensor([[[597.8172, 894.6785]]]),
 tensor([[[ 828.4139, 1853.6736]]]),
 tensor([[[  226.0106, -1018.5403]]]),
 tensor([[[1994.9950, 6174.8740]]]),
 tensor([[[ -2903.6455, -13136.2568]]]),
 tensor([[[10917.8076, 36676.0664]]]),
 tensor([[[-29450.9258, -93312.3594]]]),
 tensor([[[ 86699.4688, 243709.0000]]]),
 tensor([[[-246646.8906, -628298.2500]]]),
 tensor([[[ 739073.2500, 1645480.5000]]]),
 tensor([[[-2385644.5000, -4320317.0000]]]),
 tensor([[[ 7071482., 11239530.]]]),
 tensor([[[-20403056., -27931576.]]])]

In [39]:
gt

[tensor([[[ 587.6106, 1381.2997]]]),
 tensor([[[ 587.6106, 1381.2997]]]),
 tensor([[[ 586.9632, 1380.9113]]]),
 tensor([[[ 586.6739, 1380.7225]]]),
 tensor([[[ 586.3462, 1380.4492]]]),
 tensor([[[ 585.7589, 1379.9354]]]),
 tensor([[[ 585.4659, 1379.6121]]]),
 tensor([[[ 584.9191, 1379.0210]]]),
 tensor([[[ 584.6808, 1378.6652]]]),
 tensor([[[ 584.3546, 1378.2303]]]),
 tensor([[[ 583.8191, 1377.5601]]]),
 tensor([[[ 583.6369, 1377.1196]]]),
 tensor([[[ 583.3925, 1376.6952]]]),
 tensor([[[ 582.9846, 1375.8479]]]),
 tensor([[[ 582.7881, 1375.3280]]]),
 tensor([[[ 582.6030, 1374.8840]]]),
 tensor([[[ 582.4222, 1374.3217]]]),
 tensor([[[ 582.2029, 1373.8376]]]),
 tensor([[[ 582.0811, 1373.3918]]]),
 tensor([[[ 581.8999, 1372.7820]]]),
 tensor([[[ 581.7318, 1372.3556]]])]

In [31]:
prediction_gt.keys()

dict_keys([])